### ISSUE TITLE
no such file or directory, open `'[...]/dist/css/preflight.css'`

### ISSUE THREAD

**Issue by markokajzer** [Trapfether/tailwind-raw-reorder#4]
Hey! I would love to use your extension, since https://github.com/heybourn/headwind is completely unmaintained, but I'm encountering the following issue 😭

Let me know if you need anything else!

**Describe the bug**

When running the sort command (either through the command panel or by saving the file) I get the following error (also see screenshot)

> A system error occurred (ENOENT: no such file or directory, open '/Users/amaterasu/.vscode/extensions/trapfether.tailwind-raw-reorder-3.0.3/dist/css/preflight.css')

**To Reproduce**

1. Install extension
2. Create basic html file, e.g. `<div class="py-3 block"></div>`
3. Save or run command

**Expected behavior**
Tailwind classes are sorted

**Screenshots**
![Screenshot 2023-10-23 at 08 42 29](https://github.com/Trapfether/tailwind-raw-reorder/assets/9379317/d7fdbd2a-8bbd-4764-9378-c2ac73eaf5a5)

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.5.2
 - Extension version: v3.0.3

**Comment by kg-currenxie** [comment]
Same here

**Comment by intrepidws** [comment]
Samesies

**Comment by Trapfether** [comment]
I'm looking into this. It appears that the issue described occurs when no local tailwind config can be found for the file. The extension is meant to use the default tailwind config in this case, but that is not happening as expected. I anticipate I'll have this figured out this week.

If anyone else is encountering this issue that HAS a local tailwind config for the impacted file, please expand on you situation here.

As a temporary work-around for those impacted, you can put a basic tailwind.config.js file at the base directory of your project.

**Comment by Trapfether** [comment]
Here is the update. The extension was updated to version 3.1.0 today. This fixes the preflight not found exception.

However, The extension requires a local tailwind.config file to function correctly and will show the user an error if none is found. This is so that the extension won't touch workspaces that are not using tailwind at all. I cannot imagine the frustration that would occur if a non-tailwind project suddenly had classes moving around because they accidently overlap with tailwind classes.

This means that in the future if we add options for ordering custom / unknown classes (the current behavior is that custom classes are left in their current order) we won't accidently stomp all over someone's non-tailwind project because they flipped that switch globally. 

You can use a dummy config file and include it in your .gitignore if you're just looking for local functioning and don't want to include the tailwind config in your repo for some reason.

I will leave this issue open for a few days in case people want to respond to how I went about this. If you have any feedback, I'd be glad to hear it.
