### ISSUE TITLE
Doesn't respect classes inside single quotes? (in AlpineJS)

### ISSUE THREAD

**Issue by kg-currenxie** [Trapfether/tailwind-raw-reorder#7]
Having a case like this:
```
<div x-bind:class="loading ? 'disabled:bg-button-filled-surface-enabled disabled:text-on-button-on-filled-enabled' : 'cursor-not-allowed disabled:bg-button-filled-surface-disabled disabled:border-button-filled-stroke-enabled disabled:border-button-filled-stroke-disabled disabled:text-on-button-on-filled-disabled'">
```

after saving, it becomes this:
```
<div x-bind:class="loading ? 'disabled:bg-button-filled-surface-enabled disabled:text-on-button-on-filled-enabled' : 'cursor-not-allowed disabled:bg-button-filled-surface-disabled' disabled:border-button-filled-stroke-enabled disabled:border-button-filled-stroke-disabled disabled:text-on-button-on-filled-disabled">
```
as you see, the quote breaks here: `...ed-surface-disabled' disabled:border-b...`

is there a way to do this? the regex seems a bit complex :|

**Comment by Trapfether** [comment]
The Regex is pretty gnarly I'll admit.

What is going on here is that everything within double quotes is being treated as a space delaminated classname string, so the single quote is being treated as part of the disabled:text-on-button-on-filled-disabled class.

You can disable this behavior by changing the html regex from:
"class=(([\"'`])(?:(?:[^{}<>](?!\\2))|\\\\\\2)+[^{}<>])\\2" to
"\\sclass=(([\"'`])(?:(?:[^{}<>](?!\\2))|\\\\\\2)+[^{}<>])\\2"

which will require a space before the class property in order to match. This will make it so that x-bind:class no longer matches that regex.

Then you can look at adding an additional regex that targets the x-bind:class format itself. You'll want to be fairly specific so in this case I would try and craft your regex to only match the ternary operator with two string literal results wrapped in single quotes.

In my next update, I will make the space before the class property the default html regex so it won't accidentally break alpine JS and similar binding tools that use the prefix:class format

**Comment by kg-currenxie** [comment]
Thx :)

Another workaround for Alpine people that might come across this issue, is to use the object syntax rather than ternary operator:

```
:class="{
  'my list of classes': boolean,
  'my-other-list different-class': !boolean
}
```

**Comment by Trapfether** [comment]
@kg-currenxie Thank you for the alternative. I'll leave this issue open until the default has been changed

**Comment by Trapfether** [comment]
With today's update to version 3.1.0, the bound class should no longer match by default.

I will probably examine making some options for enabling ternary support in alpine js in the future.
