### ISSUE TITLE
Adding custom location for config?

### ISSUE THREAD

**Issue by kg-currenxie** [Trapfether/tailwind-raw-reorder#9]
Would it be possible to add an option to add folders to look in?

Using tailwind in rails unfortunately has the config in `config/tailwind.config.js`
https://github.com/rails/tailwindcss-rails

The workaround is to do
```
const config = require('./config/tailwind.config.js')

module.exports = config
```

but seems a bit meh :P

**Comment by Trapfether** [comment]
That is an in interesting situation for sure.

Is that standard in all rails apps? it may be better for us to auto-detect the framework if that is the case. If that isn't the case, then I think a config option is in fact the way to go. I'd be slightly hesitant as setting the default override rather than the workspace specific setting could lead people to accidently break their OTHER workspaces that use different frameworks.

I could also see about just checking to see if a config folder exists at the base workspace directory and check in their for tailwind.config.* if it wasn't found in the hierarchy already (tailwind like some other tools is built around the idea that the closest ancestor config for a given file is the one used to configure the tool for the file in question)

Let me know your feedback on these thoughts and I'll figure out a satisfactory fix. Thank you for bringing this pain point to my attention!

**Comment by kg-currenxie** [comment]
Yes, this is the standard for rails. i think auto-detecting would add too much coupling

what if the plugin option was just defaulted to

`config = ['./tailwind.config.js']` and then i could chose to change it to
`config = ['./tailwind.config.js', './config/tailwind.config.js']`

it wouldnt break any other workspace as it would just check all paths 🤔

**Comment by Trapfether** [comment]
There is now an option in the latest update that allows for specifying a path to the tailwind config file. It can be relative to the workspace folder, or an absolute path. If you always use the same project structure, then setting this globally is probably the best. If you have different structures between projects, setting this in your directory-specific settings is the recommended approach.
